name: pytorch_sac_ae
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - absl-py
  - pyparsing
  - pip
  - pip:
    - termcolor
    - dm_control
    - tb-nightly
    - tensorboard
    - imageio
    - imageio-ffmpeg
